language: csharp
solution: Searchlight.sln

jobs:
  include:
    - dotnet: 6.0.100
      mono: none
      script:
        - dotnet build ./tests/Searchlight.Tests/Searchlight.Tests.csproj
        - dotnet test ./tests/Searchlight.Tests/Searchlight.Tests.csproj
