name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Check Environment Variables (RUNNER_TEMP)
      run: echo "Runner Temp is ${{env.RUNNER_TEMP}}"
    - name: Check Environment Variables (TMP)
      env: 
        TMP: ${{env.RUNNER_TEMP}}
      run: echo "DotNet TMP is ${{env.TMP}}"
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      env: 
        TMP: ${{env.RUNNER_TEMP}}
      run: dotnet test
